version: '2'

services:
  postgresql_dev:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=diet
      - POSTGRESQL_USERNAME=username
      - POSTGRESQL_PASSWORD=randompassword
      - POSTGRESQL_POSTGRES_PASSWORD=masterPassword
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/bitnami/postgresql
  
  postgresql_test:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=diet
      - POSTGRESQL_USERNAME=username
      - POSTGRESQL_PASSWORD=randompassword
      - POSTGRESQL_POSTGRES_PASSWORD=masterPassword
    ports:
      - '5433:5432'
    volumes:
      - postgresql_data_test:/bitnami/postgresql

volumes:
  postgresql_data:
  postgresql_data_test: